// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // URL usada pelo CLI (migrate/generate). Em runtime o PrismaClient usa um
  // driver adapter (@prisma/adapter-pg) — ver src/lib/db.ts.
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
